apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-exporter

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: log-exporter
rules:
- apiGroups: [""]
  resources:
    - "pods/log" 
    - "pods"
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: log-exporter
subjects:
- kind: ServiceAccount
  name: log-exporter
  namespace: default
roleRef:
  kind: ClusterRole
  name: log-exporter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: log-exporter
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: log-exporter
        spec:
            serviceAccountName: log-exporter             
            containers:
            - env:
                - name: NAMESPACE
                  value: "qa,perf"  # replace with the namespaces you have created with fargateprofile
                - name: LOKI_URL
                  value: http://loki.loki:3100
                - name: IGNORE_APPS
                  value: "log-exporter,bull-exporter" # replace with any apps you are not interested in to get logs shipped to loki
                - name: IGNORE_CONTAINERS
                  value: "metrics" # any container names you know you dont want
              name: log-exporter
              image: lucidprogrammer/log-exporter:latest
            #   image: datawire/telepresence-k8s:0.103 # you can use this to do local development
              imagePullPolicy: Always
        